[default]

project_name = "Portfolio API"

# MONGO

mongo_hostname = "mongo"
mongo_port = 27017
mongo_username = ""
mongo_password = ""
mongo_ssl = false
mongo_database = "portfolio"
mongo_options_uuidrepresentation = "standard"
mongo_experience_collection = "experiences"
