[default]

project_name = "Portfolio API"
environment = "dev"

# JWT
jwt_secret_key = ""
jwt_algorithm = "HS256"
jwt_password = ""
jwt_expiration_minutes = 3

# MONGO
mongo_hostname = "mongo"
mongo_username = ""
mongo_password = ""
mongo_port = 27017
mongo_ssl = false
mongo_database = "portfolio"
mongo_options_uuidrepresentation = "standard"
mongo_experience_collection = "experiences"
